# Generated by Django 6.0.7 on 2026-07-31 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('review', 'Review'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], max_length=32)),
                ('to_state', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('review', 'Review'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], max_length=32)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='application_applica_89e585_idx')],
            },
        ),
    ]
