# Generated by Django 6.0.7 on 2026-07-26 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('corrected_value', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('accepted', 'Accepted'), ('edited', 'Edited'), ('rejected', 'Rejected')], db_index=True, default='unreviewed', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.document')),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('document', 'key'), name='uniq_document_field_key')],
            },
        ),
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_jobs', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='extraction__documen_bc9036_idx')],
            },
        ),
    ]
